server:
  port: 19090   # local 환경에서는 19090 포트로 실행

spring:
  datasource:
    # secret-key는 환경변수로 설정
    url: jdbc:p6spy:mariadb://localhost:3306/SeedBEAppDB
    username: ENC(hQiz+S56g0lxwDtqy2pkFBIYalru1mZcmQv894o8uV5Ol2el+sH6tiGKQ7QdMDYP)                                 # 사용자명 (예시)
    password: ENC(0rC5ohNoxi5U68zaKGRLL1wt0jSXeoMfyWLNlD9M9hWzMY0H/GGfWTGVCvy9Obuq)                                 # 비밀번호 (예시)
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver #org.mariadb.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 50MB     # 하나의 파일의 최대 사이즈
      max-request-size: 60MB  # 한번의 요청으로 허용가능한 여러개 파일의 합계 사이즈

# JPA 로그는 끕니다(사용 중이어도 P6Spy가 찍으므로 중복 방지)
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: false
#    properties:
#      hibernate.format_sql: false

# ★ datasource-proxy(데코레이터) 쪽 로깅은 전부 끔 (의존성은 유지)
decorator:
  datasource:
    enabled: false
    # 데코레이터 자체는 유지하되, 로깅 기능만 비활성화
    datasource-proxy:
      enabled: false
    p6spy:
      enable-logging: false

logging:
  level:
    p6spy: INFO
    com.p6spy: INFO
    # datasource-proxy가 혹시라도 남기는 로그 완전 차단
    # net.ttddyy.dsproxy: OFF
    # net.ttddyy.dsproxy.listener: OFF
    # MyBatis 자체 로그도 필요시 끌 수 있음(준비/파라미터 라인 방지용)
    org.apache.ibatis: INFO
    org.mybatis: INFO


# MyBatis 관련 설정
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

# Swagger 설정 (
#springdoc:
#  swagger-ui:
#    path: /service/swagger-ui.html

# 파일 업로드 경로
app:
  upload:
    # 윈도우/리눅스 모두 동작 가능한 기본 경로 (원하면 환경변수로 치환 가능)
    dir: ${user.home}/SeedBEApp/uploads
    uriPrefix: /files   # 다운로드/정적서빙용 URL prefix