spring:
  application:
    name: SeedBEApp

  profiles:
    active: local   # 실행 시 local 프로파일을 기본 활성화

server:
  port: 8080        # 기본 포트 (로컬이 아닐 때는 8080)

mybatis:
  mapper-locations: classpath:/mappers/**/**/*.xml
  type-aliases-package: com.heyso.SeedBEApp
  configuration:
    map-underscore-to-camel-case: true