spring:
  application:
    name: SeedBEApp

  output:
    ansi:
      enabled: ALWAYS   # 이 부분이 있어야 logback 로그에 색상이 표현됨

  profiles:
    active: local   # 실행 시 local 프로파일을 기본 활성화

server:
  port: 8080        # 기본 포트 (로컬이 아닐 때는 8080)

mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
  type-aliases-package: com.heyso.SeedBEApp
  type-handlers-package: com.heyso.SeedBEApp.common.typehandler
  configuration:
    map-underscore-to-camel-case: true

app:
  security:
    jwt:
      issuer: SeedBEApp
      access-exp-min: 60 # Access 토큰 만료(분)
      secret: ${JWT_SECRET:GVHRibT6J5RJmuOI3a5+osjQ/HaQXQg+ZZMmKzdIjw4=} # 운영은 환경변수 사용