CREATE TABLE IF NOT EXISTS TB_BOARD_FILE (
  FILE_ID        BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '파일 PK',
  BOARD_ID       BIGINT NOT NULL COMMENT '게시물 PK',
  ORG_FILE_NM    VARCHAR(255) NOT NULL COMMENT '원본 파일명',
  STORED_FILE_NM VARCHAR(255) NOT NULL COMMENT '서버 저장 파일명(UUID)',
  FILE_EXT       VARCHAR(50)  NULL COMMENT '확장자',
  MIME_TYPE      VARCHAR(100) NULL COMMENT 'MIME 타입',
  FILE_SIZE      BIGINT       NOT NULL COMMENT '파일 크기(Byte)',
  FILE_PATH      VARCHAR(500) NOT NULL COMMENT '저장 경로',
  USE_YN         CHAR(1)      NOT NULL DEFAULT 'Y',
  RGST_ID        VARCHAR(50)  NULL,
  RGST_DTM       DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  MDFC_ID        VARCHAR(50)  NULL,
  MDFC_DTM       DATETIME     NULL ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT FK_TB_BOARD_FILE__BOARD
    FOREIGN KEY (BOARD_ID) REFERENCES TB_BOARD(BOARD_ID)
      ON DELETE CASCADE
) COMMENT='게시물 첨부파일';

CREATE INDEX IX_TB_BOARD_FILE__BOARDID ON TB_BOARD_FILE (BOARD_ID);