-- 게시판 테이블 및 인덱스 생성 스크립트
-- 작성일: 2025-09-02
-- 설명: 게시판 테이블(TB_BOARD) 및 기본 인덱스 정의
CREATE TABLE TB_BOARD (
    BOARD_ID   BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '게시글 ID',
    CATEGORY   VARCHAR(10)   NOT NULL COMMENT '카테고리',
    TITLE      VARCHAR(300)  NOT NULL COMMENT '제목',
    CONTENTS    MEDIUMTEXT    NOT NULL COMMENT '본문 (Markdown 지원)',
    USE_YN     VARCHAR(1)    NOT NULL DEFAULT 'Y' COMMENT '사용 여부 (Y: 공개, N: 비공개)',
    RGST_ID    VARCHAR(30)   NOT NULL COMMENT '등록자',
    RGST_DTM   DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '등록일시',
    MDFC_ID    VARCHAR(30)   NULL COMMENT '수정자',
    MDFC_DTM   DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE current_timestamp COMMENT '수정일시',
    CONSTRAINT CK_TB_BOARD_USE_YN CHECK (USE_YN IN ('Y','N'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='게시판 테이블';