CREATE TABLE IF NOT EXISTS TB_COM_ERROR_LOG (
  ID            BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'PK',
  OCCURRED_AT   DATETIME(3)     NOT NULL COMMENT '발생일시',
  TRACE_ID      VARCHAR(50)     NOT NULL COMMENT '트레이스ID',
  STATUS        INT             NOT NULL COMMENT 'HTTP 상태코드',
  ERROR_CODE    VARCHAR(100)    NULL COMMENT '애플리케이션 에러 코드',
  MESSAGE       VARCHAR(1000)   NULL COMMENT '예외 메시지',
  PATH          VARCHAR(255)    NULL COMMENT '요청 경로',
  HTTP_METHOD   VARCHAR(10)     NULL COMMENT 'HTTP 메서드',
  QUERY_STRING  VARCHAR(1000)   NULL COMMENT '쿼리스트링',
  HEADERS_JSON  JSON            NULL COMMENT '요청 헤더 (JSON)',
  BODY_TEXT     MEDIUMTEXT      NULL COMMENT '요청 본문',
  STACKTRACE    MEDIUMTEXT      NULL COMMENT '스택트레이스',
  PRIMARY KEY (ID),
  KEY IDX_ERROR_LOG_TRACE_TIME (TRACE_ID, OCCURRED_AT)
) ENGINE=InnoDB
  DEFAULT CHARSET=utf8mb4
  COLLATE=utf8mb4_general_ci;