ALTER TABLE TB_BOARD
    MODIFY COLUMN RGST_ID BIGINT NULL,
    MODIFY COLUMN MDFC_ID BIGINT NULL;

ALTER TABLE TB_BOARD_FILE
    MODIFY COLUMN RGST_ID BIGINT NULL,
    MODIFY COLUMN MDFC_ID BIGINT NULL;

-- (선택) FK 제약 추가 (운영 환경 정책에 따라 사용/제외)
-- FK 이름은 팀 네이밍 규칙에 맞게 변경 가능
ALTER TABLE TB_BOARD
    ADD CONSTRAINT FK_BOARD_RGST
        FOREIGN KEY (RGST_ID) REFERENCES TB_COM_USER (USER_ID),
    ADD CONSTRAINT FK_BOARD_MDFC
        FOREIGN KEY (MDFC_ID) REFERENCES TB_COM_USER (USER_ID);

ALTER TABLE TB_BOARD_FILE
    ADD CONSTRAINT FK_BOARD_FILE_RGST
        FOREIGN KEY (RGST_ID) REFERENCES TB_COM_USER (USER_ID),
    ADD CONSTRAINT FK_BOARD_FILE_MDFC
        FOREIGN KEY (MDFC_ID) REFERENCES TB_COM_USER (USER_ID);