CREATE TABLE IF NOT EXISTS TB_USER (
    USER_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    USERNAME VARCHAR(100) NOT NULL UNIQUE,
    PASSWORD_HASH VARCHAR(200) NOT NULL,
    NAME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(200),
    USE_YN CHAR(1) DEFAULT 'Y',
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;


-- 권한(역할)
CREATE TABLE IF NOT EXISTS TB_ROLE (
    ROLE_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    ROLE_KEY VARCHAR(50) NOT NULL UNIQUE -- 예: ROLE_USER, ROLE_ADMIN
) DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;


-- 사용자-권한 매핑
CREATE TABLE IF NOT EXISTS TB_USER_ROLE (
    USER_ID BIGINT NOT NULL,
    ROLE_ID BIGINT NOT NULL,
    PRIMARY KEY (USER_ID, ROLE_ID),
    FOREIGN KEY (USER_ID) REFERENCES TB_USER(USER_ID),
    FOREIGN KEY (ROLE_ID) REFERENCES TB_ROLE(ROLE_ID)
) DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;